SEED: 42

data_dir: ./data/
models_dir: ./models/
metrics_dir: ./metrics/
logs_dir: ./logs/
plots_dir: ./plots/

log_level: INFO


total_mass:
  mean: 214.980074
  std: 161.497428


text_aug:
  ingr_separator: ", "
  drop_ingr:
    f_ingr: 0.1
    p: 0.5
  shuffle_ingr:
    p: 0.5


albumentations:
  train:
    - name: LongestMaxSize
      max_size: 256
      p: 1.0
    - name: PadIfNeeded
      min_height: 256
      min_width: 256
      value: 0,
      position: "random"
      fill: 0
      border_mode: 0
      p: 1.0
    - name: RandomCrop
      height: 224
      width: 224
      p: 1.0
    - name: HorizontalFlip
      p: 0.5
    - name: VerticalFlip
      p: 0.5
    - name: RandomRotate90
      p: 0.5
    - name: Affine
      scale: [0.8, 1.2]
      rotate: [-15, 15]
      translate_percent: [-0.1, 0.1]
      shear: [-10, 10]
      fill: 0
      p: 0.8
    - name: CoarseDropout
      num_holes_range: [2, 8]
      hole_height_range: [16, 32]
      hole_width_range: [16, 32]
      fill: 0
      p: 0.5
    - name: ColorJitter
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue_range: [-0.1, 0.1]
      p: 0.7
    - name: Normalize
      mean: 0.5
      std: 0.5
      p: 1.0
    - name: ToTensorV2
      p: 1.0

  test:
    - name: LongestMaxSize
      max_size: 256
      p: 1.0
    - name: PadIfNeeded
      min_height: 224
      min_width: 224
      value: 0,
      position: "center"
      p: 1.0
    - name: CenterCrop
      height: 224
      width: 224
      p: 1.0
    - name: Normalize
      mean: 0.5
      std: 0.5
      p: 1.0
    - name: ToTensorV2
      p: 1.0


model:
  image_backbone: google/vit-base-patch16-224
  text_backbone: google-bert/bert-base-uncased
  embed_dim: 768
  num_heads: 8
  dropout: 0.1
  train_n_layers: 2
  return_dict: True

training:
  device: cuda
  batch_size: 32
  epochs: 100
  weight_decay: 0.01
  image_backbone_lr: 1e-4
  lr: 1e-3
  warmup_ratio: 0.1
  num_workers: 4

  MLFlow:
    tracking_uri: "sqlite:///mlflow.db"
    experiment_name: CaloricContent
    run_name: CaloricContent
